= node-doodles

messing with node.js as a learning exercise and to make note of things so i don't have to figure them out twice.  evenutal goal: generative twitter bot(s).

inspiration: http://tinysubversions.com/2012/05/how-i-built-metaphor-a-minute/

== Usage

* make a file called `.env` with the twitter api keys in it
* to run locally:
** `foreman start`

If you know what you're doing you can figure out how to get these to run on Heroku, but it is less than ideal for various reasons.

== Bots:

=== /cell_automata

tweets random cellular automata with random colors

=== /doodle_ebooks

tweets random sentences from The King in Yellow with emoji-words replaced

=== /ommanipadmehum

tweets the mantra "om mani padme hum" every hour.  glitches the phrase randomly each time.

== /ca 

cellular automata. uses `npm install pngjs` ( https://en.wikipedia.org/wiki/Elementary_cellular_automaton )

== /emoji

find and replace emoji words in source text.  uses `npm install emoji`.

== /markov

generate basic markov chains from source text.  uses `npm install markovchain`.

== /texts

keep all source texts in one place.  source: http://www.gutenberg.org/

== /twit

use `twit` to tweet a sentence.  use `node-twitter` to tweet with an attached image.

== TODO

* improve or swap out markovchain
