= node-doodles

messing with node.js as a learning exercise and to make note of things so i don't have to figure them out twice.  evenutal goal: generative twitter bot(s).

inspiration: http://tinysubversions.com/2012/05/how-i-built-metaphor-a-minute/

== Usage

Some minimal attention has been paid to make this work on Heroku.

* make a file called `.env` with the twitter api keys in it
* to run locally:
** `foreman start`
* to run on heroku:
** `heroku create`
** if it didn't do this already, then manually do `git remote add heroku <appname's giturl>` ( find out <appname's giturl> with `heroku info` )
** `heroku config:push` this pushes the `.env` vars; require the `heroku-config` plugin
** `git push heroku master` 
** `heroku ps:scale web=1`

== /ca 

ascii cellular automata. ( https://en.wikipedia.org/wiki/Elementary_cellular_automaton )

== /emoji

find and replace emoji words in source text.  uses `npm install emoji`.

== /markov

generate basic markov chains from source text.  uses `npm install markovchain`.

== /png 

generate a png from data. uses `npm install pngjs`

== /texts

keep all source texts in one place.  source: http://www.gutenberg.org/

== /twit

use `twit` to tweet a sentence.  use `node-twitter` to tweet with an attached image.

== TODO

* improve or swap out markovchain
